from __future__ import annotations

from typing import Protocol


class OutputHandler(Protocol):
    def on_llm_start(self, depth: int) -> None: ...
    def on_llm_response(self, response: dict) -> None: ...
    def on_llm_thought(self, thought: str, depth: int) -> None: ...
    def on_vision_start(self, filename: str) -> None: ...
    def on_system_prompt(self, prompt: str) -> None: ...
    def on_action_start(self, action_type: str) -> None: ...
    def on_tool_result(self, action_type: str, result: str) -> None: ...
    def on_state_update(self, state: dict) -> None: ...
    def on_task_progress(self, message: str) -> None: ...
    def on_task_start(self, task_type: str, source: str) -> None: ...
    def on_task_complete(self, task_type: str, source: str, success: bool) -> None: ...
    def on_tokens_used(self, count: int) -> None: ...
    def on_sync_start(self) -> None: ...
    def on_sync_end(self) -> None: ...
    def display(self, content: str) -> None: ...
