from __future__ import annotations

from typing import Protocol


class OutputHandler(Protocol):
    def on_llm_response(self, response: dict) -> None: ...
    def on_system_prompt(self, prompt: str) -> None: ...
    def on_action_start(self, action_type: str) -> None: ...
    def on_state_update(self, state: dict) -> None: ...
    def display(self, content: str) -> None: ...
